const COMMENTS_PER_PAGE = 5;
const MAX_HASHTAGS_COUNT = 5;
const MAX_COMMENT_LENGTH = 140;
const REGEXP = /^#[a-zа-яё0-9]{1,19}$/i;
const ALERT_SHOW_TIME = 5000;
const MAX_UNIQUE_PICTURES = 10;
const RERENDER_DELAY = 500;
const MIN_SCALE = 25;
const MAX_SCALE = 100;
const SCALE_STEP = 25;

export {
  COMMENTS_PER_PAGE, MAX_HASHTAGS_COUNT, MAX_COMMENT_LENGTH, REGEXP,
  ALERT_SHOW_TIME, MAX_UNIQUE_PICTURES, RERENDER_DELAY, MIN_SCALE, MAX_SCALE, SCALE_STEP
};
