const COMMENTS_PER_PAGE = 5;
const MAX_HASHTAGS_COUNT = 5;
const MAX_COMMENT_LENGTH = 140;
const REGEXP = /^#[a-zа-яё0-9]{1,19}$/i;
const ALERT_SHOW_TIME = 5000;

export { COMMENTS_PER_PAGE, MAX_HASHTAGS_COUNT, MAX_COMMENT_LENGTH, REGEXP, ALERT_SHOW_TIME };
